# Generated by Django 4.2.6 on 2023-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='index/img')),
                ('name', models.TextField()),
                ('cost', models.IntegerField()),
                ('tutor', models.CharField(max_length=200)),
                ('time', models.FloatField()),
                ('count', models.IntegerField()),
                ('numb', models.IntegerField()),
            ],
        ),
    ]
