# Generated by Django 4.2.6 on 2023-12-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='index/img')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
