# Generated by Django 4.2.6 on 2023-12-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
